### ISSUE TITLE
3.4.1: Relative assets urls are converted into absolute ones. Breaking existing code.

### ISSUE THREAD

**Issue by tvdeyen** [rails/sprockets-rails#486] opened 2021-11-24 15:26 UTC
In https://github.com/rails/sprockets-rails/commit/05dbab27d54f58a7a505498863dd0d88a6b32389 a breaking change was introduced and released as 3.4.1 as a hotfix for the already breaking 3.4.0

Before sprockets 3.3.0 a url like `url(img/thing.gif)` inside a folder loads the image from the current folder (the folder the file lives in) relatively. This is valid HTML/CSS and every css processor reads this correctly.

Now the url is converted into an absolute URL. This breaks a lot of existing frontend code. In a patch level release by the way.

Can we revert this please and release a new version? Then rethink changes made in 3.3.0 and 3.4.0 and release them as a 4.0 instead if a breaking change is intentional/necessary?

**Comment by tvdeyen** [comment] 2021-11-24 15:36
You can see the breakage in this failing CI https://github.com/AlchemyCMS/alchemy_cms/runs/4300052710?check_suite_focus=true#step:12:127

and what was necessary to fix it

https://github.com/AlchemyCMS/alchemy_cms/pull/2218/files

as you can also see we have to use a relative url starting from the top most folder (the sprockets lookup path) but it is then turned into an absolute url.

Both behaviors seem wrong from what a browser (and a file system) would usually do.

## Expected behavior:

```css
url("img/some.gif")
```

from a file in a folder `app/assets/stylesheets/components/style.css`

should return a url 

```css
url("/assets/components/img/some.gif")
```

and not

```css
url("/assets/img/some.gif")
```

while a 

```css
url("/img/some.gif")
```

should return

```css
url("/assets/img/some.gif")
```

**Comment by rafaelfranca** [comment] 2021-11-25 23:28
@jcoyne can you take a look on this one as well please? We should making the absolute path relative to the current asset, and that should fix the issue.

**Comment by jcoyne** [comment] 2021-11-29 15:46
@rafaelfranca yes, I'll take a look today.

**Comment by jcoyne** [comment] 2021-11-29 21:17
@tvdeyen is this still an issue after https://github.com/rails/sprockets-rails/pull/485?

**Comment by nickcoyne** [comment] 2021-11-29 22:27
I see [this issue](https://github.com/rails/sprockets-rails/pull/485) in versions 3.3.0, 3.4.0 and 3.4.1. No problems on 3.2.2.

**Comment by jcoyne** [comment] 2021-11-30 03:02
@nickcoyne the code from #485 hasn't yet been released, but it is in the main branch.

**Comment by nickcoyne** [comment] 2021-11-30 03:32
ok, thanks @jcoyne, I'll give that a try then.

**Comment by valscion** [comment] 2021-11-30 07:42
This issue still affects us even with the changes in #485. Previously `sprockets-rails` output the filenames as relative and now the change to paths being absolute breaks our build.

I don't really understand the reasoning behind this change and why these tests are the expected ones:

https://github.com/rails/sprockets-rails/blob/4e0f1686ce108ea3a52fb0dfb24bb6272ea2df3f/test/test_asset_url_processor.rb#L52-L63

Is there any way to make sprockets-rails still output the paths as relative like it used to do before v3.3.0? Our asset pipeline relied on sprockets-rails outputting the relative paths and the change in v3.3.0 seems to have made that impossible.

**Comment by jcoyne** [comment] 2021-11-30 13:47
@valscion This is all driven by the new Rails 7 asset pipeline, which primarily uses sprockets-rails as a post-processor for cssbundling-rails.  It was the fix for https://github.com/rails/cssbundling-rails/issues/22

**Comment by jcoyne** [comment] 2021-11-30 14:21
@rafaelfranca I'm way out of my depth here. I've looked but I'm not sure how to go about this.

**Comment by valscion** [comment] 2021-11-30 14:37
Ok well good to know that this is driven by Rails 7 needs :+1:. We'll pin our version to 3.2.2 as this backwards-incompatible change was released in v3.3.0 ☺️

**Comment by tvdeyen** [comment] 2021-11-30 14:58
> We'll pin our version to 3.2.2 as this backwards-incompatible change was released in v3.3.0 ☺️

As I asked above, can we bump the version to `4.0.0.pre` with the changes for Rails 7 and revert the breaking changes from 3.3, 3.4 and release them as 3.3.1 and 3.4.2?

Then we can pin our projects to `sprockets-rails ["~> 3.3", "< 4.0"]` and Rails 7 can start using `4.0.0pre`

@rafaelfranca @dhh are you fine with that?

**Comment by jcoyne** [comment] 2021-11-30 15:09
@tvdeyen We use cssbundling-rails + sprockets-rails on a rails 6.1 app, so that would cause a breaking change for us.

**Comment by tvdeyen** [comment] 2021-11-30 15:24
@jcoyne could you use proposed 4.0.0.pre in your Rails 6.1 as well? I am not saying that `sprockets-rails` 4.0 should only work with Rails 7, but that Rails 7 uses sprockets-rails 4 as default if the breaking changes are necessary for Rails 7.

**Comment by jcoyne** [comment] 2021-11-30 15:38
@tvdeyen So that everyone better understands the AlchemyCMS use case, are the tinyMCE image assets linked to without the hash digest?  It might be that using cssbundling-rails wants all image assets to be digested and your use case is expecting non-digested assets.

**Comment by tvdeyen** [comment] 2021-11-30 16:08
@jcoyne yes, but this is totally unrelated to this issue. The digest gets removed (aka a symlink created) via the ` non-digest-stupid-assets` gem. That is not the issue we are seeing. The issue is as described above with relative urls and stylesheets and their images in the same folder (a common practice in JS themes). We fixed the tinymce icon font issues by adjusting our tinymce skin to use absolute paths instead. That was an easy fix as we own the code for the skin.

But another issue we are seeing is with the fontawesome icon font (and the css bundle they provide). The paths in the stylesheet (you are downloading from their website) are all relative. With `sprockets-rails` < 3.3 everything works as expected. With 3.3 and above it broke because `sprockets-rails` converts relative paths into absolute ones.

**Comment by tvdeyen** [comment] 2021-11-30 16:19
> It does convert them to absolute paths because it is trying to make them into digested assets

`sprockets-rails` 3.3.0 was able to provide digested urls without making them absolute.

**Comment by jcoyne** [comment] 2021-11-30 16:22
@tvdeyen it didn't provide digested urls for every `url()` in the css, only those that used `image-url` or similar I believe.  With cssbundling-rails, that would have to change as it emits regular CSS.

**Comment by valscion** [comment] 2021-12-01 07:45
Yeah for us, we were relying on `sprockets-rails` to not mangle `url()` at all and let it be as it was. We are generating our CSS using a different pipeline and pass the end result through Sprockets pipeline so that we get gzipping and can use the [`asset_sync`](https://github.com/AssetSync/asset_sync) gem. The separate pipeline already adds a cache bust hash to the generated CSS filename, so we also are using [`non-stupid-digest-assets` gem](https://github.com/alexspeller/non-stupid-digest-assets) to make our application work.

The change in `sprockets-rails` v3.3.0 suddenly changed the behavior of how `url()` is handled, and that to me, too, looks like a breaking change that should've been released in a major version release and not a minor one.

And I guess that's what this issue is about — discussing semantics of version numbering. Not about whether there's some sort of a "fix" for how to keep the early behavior.

There might also be other gems that have relied, maybe on purpose, maybe by accident, on the old behavior where `url()` behavior was not changed and only `image-url` was.

It's of course up to the maintainers of `sprockets-rails` to decide how they want to version the gem ☺️.

---

And yes, the way we use sprockets and sprockets-rails can seem to be quite unorthodox. We know that our way of using sprockets and sprockets-rails can be prone to breakage when a change to the Rails builtin asset pipeline is changed. And that seems to be the case for us here in sprockets-rails gem.

For me, I'm a bit sad that we have to pin the gem to v3.2.2 but I also understand that it's a price we must pay for fiddling with the asset pipeline as much as we do.

**Comment by valscion** [comment] 2021-12-01 07:52
Seems like AlchemyCMS also uses the `non-stupid-digest-assets` gem and thus already ends up monkeypatching the way Sprockets works: https://github.com/AlchemyCMS/alchemy_cms/blob/047119d1ac8bb039452ed1fa60e15b3a387f8cec/alchemy_cms.gemspec#L48 and uses the gem with the `tinymce` part referenced in this issue: https://github.com/AlchemyCMS/alchemy_cms/blob/047119d1ac8bb039452ed1fa60e15b3a387f8cec/lib/alchemy/engine.rb#L18-L20

So the way I see it is that v3.3.0 breaks compatibility with the `non-stupid-digest-assets` gem. And that `non-stupid-digest-assets` has always been prone to breakage given that it does it's work by monkeypatching another gem.

Now that `sprockets-rails` has more features by also knowing how to handle `url()` natively without using `image-url`, the way the asset pipeline that required `non-stupid-digest-assets` to work must change. I don't know how that change will look like, though.

To me, it feels more like a burden for us end users who used `non-stupid-digest-assets` gem to figure this out. We were relying on a monkeypatch to keep our application working like it used to. And now here we are.

**Comment by jcoyne** [comment] 2021-12-01 13:59
@valscion @tvdeyen thank you for you feedback on this problem. It's clear that the committers will have to make a decision about how to move forward. Rewinding a released feature is complicated, but we also shouldn't have broken existing apps. One thing I've learned is that sprockets-rails has very little test coverage, especially integration type tests. If someone is able to add those tests, I think this project could be a lot more stable.

**Comment by dhh** [comment] 2021-12-02 13:04
In retrospect, yes, we probably should have bumped the major version. But that's more of a stylistic change. The end result would have been the same: some use patterns would have been incompatible. I don't see the trade off of reverting changes, pushing out a new 3.x release, then doing a separate 4.0 as being worth it at this point, though.

We can fix the relative-to-absolute conversion, though. So that the absolute path is translated relative to the path of the asset. @jcoyne, if you want to tackle that, please go ahead, and we can release that in 3.4.x.

**Comment by valscion** [comment] 2021-12-02 13:16
> So that the absolute path is translated relative to the path of the asset.

That might work for us, yes.

For example, we have the built CSS file living in production in here:

```
https://assets.venuu.se/assets/v2/bundle/fi/styles.433344a57edc53a908ed.css
```

And with `sprockets-rails` v3.2.2, that CSS contains this declaration for a SVG image:

```css
.cFMs319K8uCdE_4aIE3wU::before {
  content: url(static/icon-sitting-white.72e233bb0680f4a70b717dcea570e673.svg);
}
```

Now this ends up downloading the SVG from here:

```
https://assets.venuu.se/assets/v2/bundle/fi/static/icon-sitting-white.72e233bb0680f4a70b717dcea570e673.svg
```

---

With `sprockets-rails` v3.4.1 that we tested, the CSS end result was something like this:

```css
.cFMs319K8uCdE_4aIE3wU::before {
  content: url(/static/icon-sitting-white.72e233bb0680f4a70b717dcea570e673.svg);
}
```

So the place it tried to load the SVG from ended up being this one:

```
https://assets.venuu.se/static/icon-sitting-white.72e233bb0680f4a70b717dcea570e673.svg
```

...which was happily caught by our CI before it reached production.

For us, it would've been OK if the CSS ended up looking like this instead:

```css
.cFMs319K8uCdE_4aIE3wU::before {
  content: url(/assets/v2/bundle/fi/static/icon-sitting-white.72e233bb0680f4a70b717dcea570e673.svg);
}
```

We've configured our application with:

```rb
Rails.application.configure do
  config.assets.version = 'v2'
  config.assets.prefix = File.join('/assets', config.assets.version)
  config.assets.digest = true
  config.assets.precompile << ['bundle/*']
end
```

and the CSS-file-to-be-precompiled can be found in path

```
app/assets/javascripts/bundle/fi/styles.433344a57edc53a908ed.css
```

while the SVG file referenced in CSS is in path:

```
app/assets/javascripts/bundle/fi/static/icon-sitting-white.72e233bb0680f4a70b717dcea570e673.svg
```

So during precompilation, all the necessary information should be there to go from

```css
.cFMs319K8uCdE_4aIE3wU::before {
  content: url(static/icon-sitting-white.72e233bb0680f4a70b717dcea570e673.svg);
}
```

to this one:

```css
.cFMs319K8uCdE_4aIE3wU::before {
  content: url(/assets/v2/bundle/fi/static/icon-sitting-white.72e233bb0680f4a70b717dcea570e673.svg);
}
```

We'd be OK even if the end result would get the digest added to it and become something like this instead:

```css
.cFMs319K8uCdE_4aIE3wU::before {
  content: url(/assets/v2/bundle/fi/static/icon-sitting-white.72e233bb0680f4a70b717dcea570e673-331b0896fbbe3be736a015ecbb0382c7a837e7aef841467ceb5ab24bb0914d9c.svg);
}
```

**Comment by jrochkind** [comment] 2021-12-06 21:35
> It does convert them to absolute paths because it is trying to make them into digested assets. I don't think you want these to be digested assets and I don't think we have a way of deciding which assets should be digested and which shouldn't.

So, the need for digested asset references in _some_ cases of course existed before. Is it that Rails 7 with css-bundler increases the cases where you want/need this?

As I understand it/have experienced it, previously, if you wanted digested assets referenced in a CSS file, you'd have to use something like the sass-rails helper `asset-url()`, or the ERB helper `asset_url()`.  Which means you'd have to have your CSS going through SASS or ERB or something like that, yeah. 

Sprockets on it's own didn't parse `url()` references and manipulate them. So you could also have url() references to local paths that were *not* digested. That's what you'd get ordinarily, when you needed digested references you'd use one of those helpers. 

The intent of the change seemed to be to make sprockets parse CSS for _all_ `url()` references, and turn them into digested versions if possible? 

I'm not sure there's any way for that to happen backwards compatibly.   In the sense that if some people in some cases had non-digested local path references to be in their CSS, which went through sprockets, and they were relying on this... and it's now impossible?  

I guess it's not possible to meet the desired new use case, by having something in the CSS source _indicate_ that a local digested path should be looked up, instead the need is that _all_ `url()` references are to digested versions, that it be impossible to send something through sprockets with a relative path `url()` that is not a fingerprinted-path?  I may not be explaining this right, because I do not follow the details of why this is a new requirement... but it does seem impossible to achieve it with backwards compat.

**Comment by jrochkind** [comment] 2021-12-06 21:38
Could a sprockets configuration flag be added, which defaults to old behavior for backwards compat, but allows opt-in to new behavior that I guess (but don't personally understand) is necessary for use with cssbundler-rails?

**Comment by rmacklin** [comment] 2021-12-06 22:32
@jrochkind I've opened a draft PR to make this behavior configurable: https://github.com/rails/sprockets-rails/pull/489. Can you either provide an example application that reproduces the problem or simply try that PR in your application? The expected behavior would be that when using that branch, your assets work (CSS `url()` references would not be rewritten), and if you then set `Rails.application.config.assets.rewrite_css_urls` to `true` it would enable the behavior that rewrites CSS `url()` references.

**Comment by valscion** [comment] 2021-12-07 08:51
The approach in #489 would work for us and fix the issue with us not being able to upgrade ☺️

**Comment by rmacklin** [comment] 2021-12-08 01:34
@valscion Just want to clarify - were you able to test PR #489 in an application that had previously experienced broken assets when upgrading sprockets-rails?

Despite opening that PR, I actually don't work on any applications that were affected by the issue, which is why I was asking above if @jrochkind or someone else could either provide an example application or test the PR in their own private application. I was waiting to take the PR out of the draft state until someone who was affected by this issue could verify the fix.

**Comment by valscion** [comment] 2021-12-08 07:08
> were you able to test PR #489 in an application that had previously experienced broken assets when upgrading sprockets-rails?

Yes, I took that PR to a test-drive. That run passed our tests so I'm fairly confident that we'd be able to ship a version of `sprockets-rails` with the changes in #489.

**Comment by dhh** [comment] 2021-12-11 07:32
Option to turn off rewriting has been shipped in https://github.com/rails/sprockets-rails/releases/tag/v3.4.2.

**Closed by dhh** 2021-12-11 07:32 UTC
