### ISSUE TITLE
Rails.application.assets is nil in production

### ISSUE THREAD

**Issue by kirs** [rails/sprockets-rails#237] opened 2015-04-18 02:47 UTC
Now in `sprockets-rails` 3 `app.assets` is set only in case when `assets.compile` option is enabled (https://github.com/rails/sprockets-rails/blob/master/lib/sprockets/railtie.rb#L142).

By default in Rails this option is set to `false` in production environment: https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/config/environments/production.rb.tt#L27

This leads us to the bug when some gem calls `Rails.application.assets.resolve("asset.js")` in production environment and the NoMethodError is raised.

@josh does it sounds like a bug?

**Comment by josh** [comment] 2015-04-18 18:12
Thats right.

`assets.compile = false` is supposed to completely disable asset compilation. This prevents inadvertent calls to sprockets in production.

So it sounds like using those gems may have been behaving poorly in production before.

**Comment by rafaelfranca** [comment] 2015-04-19 04:13
Yeah. That looks right to me too.

@kirs do you know why the gem is doing that?

**Comment by kirs** [comment] 2015-04-26 02:21
@rafaelfranca that is `react-rails`, for instance: https://github.com/reactjs/react-rails/blob/master/lib/react/rails/railtie.rb#L15

They do it inside lambda, but it's still being called in production with `application.assets` is `nil`.

**Comment by matthewd** [comment] 2015-04-26 05:22
ISTM the ideal would be for us to provide an `application.assets` that knows how to look things up from the manifest, without doing any new compilation.

That way we could help people ignore implementation details (that, IMO, they shouldn't need to care about) like where on the filesystem the assets actually live -- basically providing a more-suitably-shaped API around [just using File.read](https://github.com/rails/sprockets/issues/35#issuecomment-95655671).

**Comment by josh** [comment] 2015-05-06 04:12
It seems like this is being fixed on the react-rails side.

**Closed by josh** 2015-05-06 04:12 UTC

**Comment by matfiz** [comment] 2016-03-31 22:25
Just as the reference for people trying to fix it in the local codebase after the update. The easy fix is to replace `Rails.application.assets.find_asset("#{asset_name}")` with `Rails.application.assets_manifest.files.values.map{|v| v['logical_path']}.include?('#{asset_name}')`

**Comment by Grammarella** [comment] 2016-06-09 20:56
matfiz, thank you very much for the helpful workaround.

**Comment by matheusvetor** [comment] 2016-06-15 15:51
Hello, my approach is different. I need to use compiled asset inline on production.
My layout uses all content inline. I need to use this way because i have a ruby client which get the html and shows on Raspberry PI.

```
doctype html
html lang="pt"
  head
    meta charset="utf-8"

  css:
    #{App::Application.assets["static.css"].to_s.html_safe}


  body
    header
      .top.full.left
        img(src="data:image/png;base64, #{@title_news_encoded}" class="margin-title-news left")
        img(src="data:image/png;base64, #{@text_encoded}" class="margin-text-news left")

        img(src="data:image/png;base64, #{@logo_big_encoded}" class="margin-logo-news right")
    section
      = yield
```

On my old Rails 4.2 app this works fine in both development and production. On my new Rails 5 app this only works on development.
Now on development ```App::Application.assets["static.css"]``` returns a ```Sprockets::Asset```.

An additional information: My new App runs on Heroku

**Comment by matheusvetor** [comment] 2016-06-16 00:14
I got to work with the following code

```
css:
  #{File.read("#{Rails.root}/public/assets/#{Rails.application.assets_manifest.files.collect{|k, v| k if v['logical_path'] == 'article.css' }.compact.first}").html_safe}
```

It is very ugly but for now was I could think

**Comment by fxtentacle** [comment] 2016-07-12 05:24
My workaround suggestion is to make your own helper in ApplicationController, which will use application.assets or application.assets_manifest as needed. Because the manifest will be empty when using the debug asset pipeline, whereas the debug .assets hash will be nil on production. And remember to use File.binread to ensure images don't get broken.
```
def self.get_asset(name)
  if Rails.application.assets
    asse = Rails.application.assets[name]
    return asse.to_s if asse 
  end
  asse = Rails.application.assets_manifest.assets[name]
  return nil unless asse
  return File.binread(File.join(Rails.application.assets_manifest.dir, asse))
end
```

**Comment by rafaelfranca** [comment] 2016-07-12 05:25
There is a method to that in sprocket-rails. `Rails.application.assets_manifest.find_sources`

**Comment by fxtentacle** [comment] 2016-07-12 06:23
Thanks @rafaelfrance. Rails.application.assets_manifest.find_sources('asset.js').first seems to return exactly what Rails.application.assets['asset.js'].to_s used to produce and it works both in dev and prod :)

**Comment by rafaelfranca** [comment] 2016-07-12 06:31
And doesn't compile the asset in production.

**Comment by hoanghuynh** [comment] 2016-09-17 13:33
Thanks @rafaelfranca @fxtentacle that works for me!

**Comment by allenmackley** [comment] 2017-01-15 23:52
@fxtentacle your solution worked great for me, thanks. 

I had to modify it slightly by putting `html_safe` to this line:
`return asse.to_s.html_safe if asse`

And then in production.rb
```
config.assets.compile = true
config.assets.css_compressor = :sass
```

**Comment by nasa42** [comment] 2017-01-18 06:51
If you are looking for an exact replacement for `asset = Rails.application.assets.find_asset(name)`, (i.e., a method that returns a `Sprockets::Asset` object, so that you can have access to methods like `content_type`), use `asset = Rails.application.assets_manifest.find(name).first`.

**Comment by nzifnab** [comment] 2017-03-30 23:09
@nasa42 `Rails.application.assets_manifest.find(name).first` gives the error:

"Sprockets::Error: manifest requires environment for compilation" which makes it sound like it's trying to recompile...

**Comment by nasa42** [comment] 2017-03-31 14:16
@nzifnab Sorry, we are no longer using that line in our app, so I don't have any more information about it.

**Comment by grosser** [comment] 2017-05-04 05:59
FYI I needed to find files that are not part of the manifest ... so switching to looking through gem dirs instead:

```Ruby
# clunky asset finder ... see https://github.com/rails/sprockets-rails/issues/237 for more
# jquery.js -> <GEM_HOME>/ruby/2.3.0/gems/rails-assets-jquery-2.2.1/app/assets/javascripts/jquery.js
def resolve_javascript(file)
  paths = Gem::Specification.stubs.map(&:full_gem_path)
  Dir.glob("{#{paths.join(",")}}/app/assets/javascripts/#{file}").first || raise("Could not find #{file}")
end
```

**Comment by mrsimo** [comment] 2017-06-15 08:34
We needed to access a compiled file within another file during precompilation, so `Rails.application.assets_manifest` didn't work the first time you run `assets:precompile`.

We solved this by doing this:

```ruby
Sprockets::Railtie.build_environment(Rails.application, true)[file_name].to_s
```

In case anyone is in the same situation that we are.

**Comment by tom-brown** [comment] 2018-12-07 22:59
I found ways to check for assets in both development and production, but neither works in both environments, so I added an application helper like this:

```
def image_exists?(path)
    if Rails.env == "development" && Rails.application.assets.find_asset(path)
      return true
    elsif Rails.env == "production" && Rails.application.assets_manifest.assets[path]
      return true
    else
      return false
    end
 end
```

Now I can check if an image_exists in both production and development before calling image_tag.  The root of the problem is image_tag throws an exception if the image doesn't exist....why not just respond nil???
