### ISSUE TITLE
Precompiling assets (with no updates) takes way too much time with sprockets rails 3.0 compared to 2.3

### ISSUE THREAD

**Issue by nathansamson** [rails/sprockets-rails#318] opened 2016-01-25 17:47 UTC
Version 3.0.0
~~~
       Running: rake assets:precompile
       Asset precompilation completed (762.04s)
       Cleaning assets
       Running: rake assets:clean
~~~

Version 2.3.3
~~~
       Running: rake assets:precompile
       Asset precompilation completed (10.66s)
       Cleaning assets
       Running: rake assets:clean
~~~

Other than that only nokogiri got a small update, as did minitest but that should not influence this

**Comment by rafaelfranca** [comment] 2016-01-25 17:48
Can you please provide a sample application that reproduces the error?

**Comment by nathansamson** [comment] 2016-01-25 17:51
I could try to, but this is on my large complex application which I can not just share.

I'll see if I can try to reproduce with an empty app with similar set of asset gems as I have in my actual app.

I'll update this later on

**Comment by rafaelfranca** [comment] 2016-01-25 17:51
Could you try to disable uglifier (if you are using it)?

**Comment by mattbrictson** [comment] 2016-01-25 20:13
Could this be related to the fact that the default cache location was changed in 3.0.0 (later fixed in https://github.com/rails/sprockets-rails/commit/2aac886a2a653204491f932b32954120f837db08)? My understanding is that would make Heroku precompiles very slow due to the cache not being maintained between deploys.

The output you posted looks like its from the Heroku buildpack, so that's my guess.

**Comment by nathansamson** [comment] 2016-01-25 20:24
Yes that would be the case... I am in deed using the heroku buildpacks.

Any ETA to get this in released persoon?
Op 25 jan. 2016 21:13 schreef "Matt Brictson" <notifications@github.com>:

**Comment by nathansamson** [comment] 2016-01-25 23:51
that was autocorrect at work, I menat released version in case that wasnt clear ;)

**Comment by rafaelfranca** [comment] 2016-01-26 02:09
no ETAs. Try master branch and see if it is fixed. I'm closing this.

**Closed by rafaelfranca** 2016-01-26 02:09 UTC
