### ISSUE TITLE
sprockets 3.0 loading jquery in resque-mailer?

### ISSUE THREAD

**Issue by petrsigut** [rails/sprockets-rails#320] opened 2016-01-27 09:18 UTC
Hi!

we are using separate groups in Bundler so the the javascript&css files are not loaded in Resque (http://engineering.harrys.com/2014/07/29/hacking-bundler-groups.html)

With sprockets-rails 2.3 it is working without problem, but with sprockets-rails 3.0 I get this error when trying to send email via Resque in development (in production it is working):

couldn't find file 'jquery' with type 'application/javascript'

Any changes how the sprockets are loading css&js files? There is obviously no need for jQuery in our emails and we do not reference it anywhere in the template...

When I move jquery gem into to "default" Bundler group, so it is loaded everywhere, it works, but the error reference then next javascript asset (jquery-ui..., cookie...). Of course, I do not want to move all js&css into default group.

I guess it is quite specific case, but I have no idea where to look  - any ideas? I really appreciate help, thanks! 

Petr

**Comment by rafaelfranca** [comment] 2016-01-29 07:06
Can you please provide a sample application that reproduces the error?

**Comment by rafaelfranca** [comment] 2016-03-02 17:22
Closing since we don't have information how to reproduce the issue.

**Closed by rafaelfranca** 2016-03-02 17:22 UTC
Labels: Need more information

**Comment by petrsigut** [comment] 2016-03-04 11:04
Sorry - we just pinned older version:

gem 'sprockets-rails', '2.3.3'

and it works...
