### ISSUE TITLE
SRI issues in Firefox

### ISSUE THREAD

**Issue by spdawson** [rails/sprockets-rails#351] opened 2016-05-24 21:47 UTC
Testing in Firefox v46.0.1. The `integrity` attributes are being correctly applied to `<script>` and CSS `<link>` tags, and the sha256 hashes are correct, and yet Firefox complains that
```
None of the "sha256" hashes in the integrity attribute match the content of the subresource.
```
It seems like this is not a Sprockets bug; has anyone else hit this problem trying to get SRI working with Firefox?

**Comment by rafaelfranca** [comment] 2016-05-24 21:57
Thank you for reporting. I believe this is a browser issue, so I'm closing this issue here.

**Closed by rafaelfranca** 2016-05-24 21:57 UTC

**Comment by connorshea** [comment] 2016-06-27 13:37
I just ran into this as well. Looks like it's caused by SCSS added a BOM to the stylesheet. Here's the relevant Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1269241
